# Site Settings
title: Nanobyte Security
email: alex@nanobytesecurity.com
description: >
  a security enthusiast trying to make a security-ish blog
baseurl: "/"
url: "http://ubghacking.github.io"
github_username: ubghacking
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
kramdown:
    input: GFM
collections:
  news:
    output: true
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
